[package]
name = "vortex"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
url = "2.5.7"
sha1 = "0.10.6"
hex = "0.4.3"
rand = "0.9.2"
percent-encoding = "2.3.2"
reqwest = "0.12.24"

tokio = { version = "1.48.0", features = ["full"] }
